---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
spec:
  selector:
    matchLabels:
      run: php-apache
  replicas: 1
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
      - name: php-apache
        image: k8s.gcr.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        env:
          - name: SOME_SECRET
            valueFrom:
              secretKeyRef:
                name: topsecret
                key: MYSECRET
        volumeMounts:
        - name: files
          mountPath: /var/www/html/env.php
          subPath: env.php
      volumes:
      - name: files
        configMap:
          name: myconfigmap
          items:
          - key: env.php
            path: env.php
