---
apiVersion: v1
kind: Pod
metadata:
  name: pod-test
  namespace: mynamespace
  labels:
    app: pod-test
spec:
  containers:
  - name: pod-test
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
