---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: standard-pvc
spec:
  accessModes:
    - ReadWriteOnce    # ReadWriteOnce, ReadOnlyMany, ReadWriteMany, ReadWriteOncePod
  storageClassName: standard
  resources:
    requests:
      storage: 128Mi

